services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspaces/genai-cohort-2:cached

    command: sleep infinity

  valkey:
    image: valkey/valkey

  vector-db:
    image: qdrant/qdrant
    ports:
    - 6333:6333